/**
 * Building and applying a recorded correction to one field of one record.
 *
 * Why this exists: several live data corrections have been made by hand with
 * no record of what changed, why, or on whose authority — so a later reader
 * finding an odd value has no way to tell a deliberate fix from a bug. Every
 * correction made through here writes its before-state to a version-
 * controlled file first, which makes it both auditable and reversible.
 *
 * Pure: no database access and no file IO, so the rules are testable on
 * their own. The caller does the reading and writing.
 */

/**
 * The fields a correction may touch, mapping the name used in
 * `manually_edited_fields` to its database column.
 *
 * Deliberately a fixed list rather than free text: a typo'd field name would
 * otherwise clear the protection on nothing and silently report success.
 */
export const CORRECTABLE_FIELDS = {
  aiSummary: "ai_summary",
  subjectArea: "subject_area",
  deliverable: "deliverable",
  timelineNotes: "timeline_notes",
  availableAnalysis: "available_analysis",
  practiceAreas: "practice_areas",
  industries: "industries",
} as const;

export type CorrectableField = keyof typeof CORRECTABLE_FIELDS;

export function isCorrectableField(name: string): name is CorrectableField {
  return Object.hasOwn(CORRECTABLE_FIELDS, name);
}

export interface CorrectionRecord {
  /** ISO date the correction was made. */
  date: string;
  eoId: string;
  eoNumber: string | null;
  eoTitle: string;
  field: CorrectableField;
  /** Why this was wrong — required, because "what changed" without "why" is not an audit trail. */
  reason: string;
  /** The value being replaced, kept verbatim so the change can be undone. */
  before: unknown;
  /** What it became. null means "cleared, to be regenerated by the pipeline". */
  after: unknown;
  /** Whether the field's entry in manually_edited_fields was removed. */
  protectionRemoved: boolean;
}

export interface RecordSubject {
  id: string;
  eoNumber: string | null;
  title: string;
  manuallyEditedFields: string[];
}

/**
 * Describes the correction without performing it. `before` is captured from
 * the caller's already-read row so the record reflects what was actually
 * there rather than what was assumed.
 */
export function buildCorrectionRecord(params: {
  subject: RecordSubject;
  field: CorrectableField;
  reason: string;
  before: unknown;
  after: unknown;
  today: string;
}): CorrectionRecord {
  const reason = params.reason.trim();
  if (!reason) {
    throw new Error("A correction needs a reason — a record of what changed without why is not an audit trail.");
  }

  return {
    date: params.today,
    eoId: params.subject.id,
    eoNumber: params.subject.eoNumber,
    eoTitle: params.subject.title,
    field: params.field,
    reason,
    before: params.before,
    after: params.after,
    protectionRemoved: params.subject.manuallyEditedFields.includes(params.field),
  };
}

/**
 * The column changes to write: the field's new value, plus
 * manually_edited_fields with this field's protection dropped so the normal
 * pipeline is free to refill it.
 *
 * Only the named field's protection is removed — every other manually edited
 * field stays protected, because a correction to one field says nothing
 * about the others.
 */
export function buildCorrectionUpdate(params: {
  subject: RecordSubject;
  field: CorrectableField;
  after: unknown;
}): Record<string, unknown> {
  return {
    [CORRECTABLE_FIELDS[params.field]]: params.after,
    manually_edited_fields: params.subject.manuallyEditedFields.filter((f) => f !== params.field),
  };
}
